language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
install:
  - python setup.py install
  - pip3 install tox-travis
script: tox

deploy:
  provider: pypi
  user: $username
  password: $password
  on:
    branch: "release"
