language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
install:
  - python setup.py install
script:
  -

deploy:
  provider: pypi
  user: $username
  password: $password
  on:
    branch: "release"
